(deftheme nimbus
  "Created 2020-01-13.")

(custom-theme-set-variables
 'nimbus
 '(ansi-color-names-vector ["#454545" "#d65946" "#6aaf50" "#baba36" "#598bc1" "#ab75c3" "#68a5e9" "#bdbdb3"]))

(custom-theme-set-faces
 'nimbus
 '(cursor ((t (:foreground "#000000" :background "#f57e00"))))
 '(fringe ((t (:inherit default :background "#212121"))))
 '(highlight ((t (:background "#114747"))))
 '(link ((t (:foreground "#86b5e8" :underline t))))
 '(link-visited ((t (:foreground "#608079" :underline t))))
 '(region ((t (:background "#11472b"))))
 '(shadow ((t (:background "gray6" :foreground "#858585"))))
 '(tooltip ((t (:foreground "#1a1a1a" :background "#bdbdb3"))))
 '(error ((t (:foreground "#ff0000" :bold t :underline nil :slant normal))))
 '(success ((t (:foreground "#9ccc65" :bold t :underline nil :slant normal))))
 '(warning ((t (:foreground "#f57e00" :bold t :underline nil :slant normal))))
 '(font-lock-builtin-face ((t (:foreground "#598bc1"))))
 '(font-lock-comment-face ((t (:foreground "#858585" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-function-name-face ((t (:foreground "#1d9a79"))))
 '(font-lock-keyword-face ((t (:foreground "#598bc1"))))
 '(font-lock-string-face ((t (:foreground "#6aaf50"))))
 '(font-lock-preprocessor-face ((t (:foreground "#df9522"))))
 '(font-lock-type-face ((t (:foreground "#d65946"))))
 '(font-lock-constant-face ((t (:foreground "#ab75c3"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-variable-name-face ((t (:foreground "#baba36"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#8fbc8f"))))
 '(button ((t (:foreground "#598bc1" :underline t))))
 '(header-line ((t (:background "#2b2b47" :foreground "#bdbdb3"))))
 '(isearch ((t (:foreground "#000000" :background "#598bc1"))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#d65946"))))
 '(match ((t (:foreground "#000000" :background "#6aaf50"))))
 '(trailing-whitespace ((t (:foreground "#ffffff" :underline t))))
 '(vertical-border ((t (:foreground "#454545"))))
 '(calendar-today ((t (:foreground "#baba36"))))
 '(calendar-month-header ((t (:foreground "#ab75c3"))))
 '(calendar-weekend-header ((t (:foreground "#608079" :slant italic))))
 '(calendar-weekday-header ((t (:foreground "#68a5e9"))))
 '(comint-highlight-prompt ((t (:foreground "#6aaf50"))))
 '(company-preview ((t (:background "#2b1147"))))
 '(company-preview-common ((t (:foreground "#a0a0a0"))))
 '(company-scrollbar-bg ((t (:background "#112b2b"))))
 '(company-scrollbar-fg ((t (:background "#114747"))))
 '(company-template-field ((t (:inherit highlight))))
 '(company-tooltip ((t (:foreground "#bdbdb3" :background "#2b2b47"))))
 '(company-tooltip-annotation ((t (:inherit font-lock-type-face))))
 '(company-tooltip-annotation-selection ((t (:inherit font-lock-type-face))))
 '(company-tooltip-common ((t (:inherit company-tooltip :foreground "#baba36"))))
 '(company-tooltip-common-selection ((t (:foreground "#bdbdb3" :background "#2b1147"))))
 '(company-tooltip-mouse ((t (:inherit company-tooltip-selection))))
 '(company-tooltip-selection ((t (:foreground "#bdbdb3" :background "#2b1147"))))
 '(compilation-info ((t (:inherit success))))
 '(compilation-warning ((t (:inherit warning))))
 '(compilation-error ((t (:inherit error))))
 '(compilation-line-number ((t (:foreground "#608079"))))
 '(compilation-mode-line-exit ((t (:inherit compilation-info))))
 '(compilation-mode-line-run ((t (:inherit compilation-warning))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error))))
 '(custom-button ((t (:inherit button :underline nil :box t))))
 '(custom-button-mouse ((t (:inherit highlight :box t))))
 '(custom-button-pressed ((t (:foreground nil :background nil))))
 '(custom-button-pressed-unraised ((t (:foreground "#ab75c3"))))
 '(custom-button-unraised ((t (:foreground nil :background nil))))
 '(custom-changed ((t (:foreground "#d65946"))))
 '(custom-comment ((t (:foreground "#1a1a1a" :background "#baba36"))))
 '(custom-comment-tag ((t (:foreground "#bdbdb3"))))
 '(custom-documentation ((t (:inherit font-lock-doc-face))))
 '(custom-face-tag ((t (:foreground "#598bc1"))))
 '(custom-group-subtitle ((t (:foreground "#ab75c3"))))
 '(custom-group-tag ((t (:foreground "#ab75c3"))))
 '(custom-group-tag-1 ((t (:foreground "#baba36" :bold t))))
 '(custom-invalid ((t (:foreground "#1a1a1a" :background "#d65946"))))
 '(custom-link ((t (:inherit link))))
 '(custom-modified ((t (:foreground "#d65946"))))
 '(custom-rogue ((t (:foreground "#baba36" :background "#1a1a1a"))))
 '(custom-saved ((t (:underline t))))
 '(custom-set ((t (:inherit widget-field))))
 '(custom-state ((t (:foreground "#df9522"))))
 '(custom-themed ((t (:foreground "#d65946"))))
 '(custom-variable-button ((t (:underline t :bold t))))
 '(custom-variable-tag ((t (:inherit font-lock-variable-name-face))))
 '(custom-visibility ((t (:inherit custom-link))))
 '(diff-added ((t (:background "#11472b"))))
 '(diff-changed ((t (:background "#2b1147"))))
 '(diff-removed ((t (:background "#47112b"))))
 '(diff-context ((t (:foreground "#757575"))))
 '(diff-file-header ((t (:foreground "#1a1a1a" :background "#959595" :bold t))))
 '(diff-function ((t (:foreground "#1a1a1a" :background "#858585"))))
 '(diff-header ((t (:inherit diff-function))))
 '(diff-hunk-header ((t (:inherit diff-function))))
 '(diff-index ((t (:inherit diff-function))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-indicator-changed ((t (:inherit diff-changed))))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(diff-nonexistent ((t (:background "#ffffff"))))
 '(diff-refine-added ((t (:inherit diff-changed :foreground "#6aaf50"))))
 '(diff-refine-changed ((t (:inherit diff-changed :foreground "#df9522"))))
 '(diff-refine-removed ((t (:inherit diff-changed :foreground "#d65946"))))
 '(dired-header ((t (:foreground "#ab75c3"))))
 '(dired-flagged ((t (:foreground "#ad3632"))))
 '(dired-symlink ((t (:foreground "#baba36"))))
 '(epa-validity-high ((t (:foreground "#9ccc65" :bold t))))
 '(epa-validity-medium ((t (:foreground "#598bc1" :bold t))))
 '(epa-validity-low ((t (:foreground "#f57e00" :bold t))))
 '(epa-validity-disabled ((t (:foreground "#ff0000" :bold t))))
 '(epa-mark ((t (:inherit dired-mark))))
 '(epa-field-name ((t (:foreground "#ab75c3"))))
 '(epa-field-body ((t (:foreground "#68a5e9"))))
 '(erc-action-face ((t (:bold t :slant italic))))
 '(erc-button ((t (:inherit link))))
 '(erc-direct-msg-face ((t (:foreground "#d65946"))))
 '(erc-input-face ((t (:foreground "#baba36"))))
 '(erc-my-nick-face ((t (:foreground "#df9522"))))
 '(erc-nick-default-face ((t (:foreground "#598bc1"))))
 '(erc-nick-msg-face ((t (:inherit erc-direct-msg-face :bold t))))
 '(erc-notice-face ((t (:foreground "#6aaf50"))))
 '(erc-prompt-face ((t (:foreground "#ab75c3"))))
 '(erc-timestamp-face ((t (:foreground "#608079"))))
 '(flycheck-info ((t (:underline (:color "#9ccc65" :style wave)))))
 '(flycheck-warning ((t (:underline (:color "#f57e00" :style wave)))))
 '(flycheck-error ((t (:underline (:color "#ff0000" :style wave)))))
 '(flycheck-fringe-info ((t (:inherit success :bold nil))))
 '(flycheck-fringe-warning ((t (:inherit warning :bold nil))))
 '(flycheck-fringe-error ((t (:inherit error :bold nil))))
 '(flycheck-error-list-info ((t (:foreground "#6aaf50"))))
 '(flycheck-error-list-checker-name ((t (:foreground "#baba36"))))
 '(flymake-note ((t (:underline (:color "#9ccc65" :style wave)))))
 '(flymake-warning ((t (:underline (:color "#f57e00" :style wave)))))
 '(flymake-error ((t (:underline (:color "#ff0000" :style wave)))))
 '(gnus-group-mail-1 ((t (:foreground "#ab75c3" :bold t))))
 '(gnus-group-mail-1-empty ((t (:foreground "#ab75c3"))))
 '(gnus-group-mail-2 ((t (:foreground "#598bc1" :bold t))))
 '(gnus-group-mail-2-empty ((t (:foreground "#598bc1"))))
 '(gnus-group-mail-3 ((t (:foreground "#ab75c3" :bold t))))
 '(gnus-group-mail-3-empty ((t (:foreground "#ab75c3"))))
 '(gnus-group-mail-low ((t (:foreground "#baba36" :bold t))))
 '(gnus-group-mail-low-empty ((t (:foreground "#baba36"))))
 '(gnus-group-news-1 ((t (:foreground "#6aaf50" :bold t))))
 '(gnus-group-news-1-empty ((t (:foreground "#6aaf50"))))
 '(gnus-group-news-2 ((t (:foreground "#9ccc65" :bold t))))
 '(gnus-group-news-2-empty ((t (:foreground "#9ccc65"))))
 '(gnus-group-news-3 ((t (:bold t))))
 '(gnus-group-news-3-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-4 ((t (:foreground nil :bold t))))
 '(gnus-group-news-4-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-5 ((t (:bold t))))
 '(gnus-group-news-5-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-6 ((t (:bold t))))
 '(gnus-group-news-6-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-low ((t (:foreground "#8fbc8f" :bold t))))
 '(gnus-group-news-low-empty ((t (:foreground "#8fbc8f"))))
 '(gnus-splash ((t (:foreground "#cccccc"))))
 '(gnus-summary-cancelled ((t (:foreground "#fffe0a" :background "#000000"))))
 '(gnus-summary-high-ancient ((t (:foreground "#86b5e8" :bold t))))
 '(gnus-summary-high-read ((t (:foreground "#9ccc65" :bold t))))
 '(gnus-summary-high-ticked ((t (:foreground "#cd9595" :bold t))))
 '(gnus-summary-high-undownloaded ((t (:foreground "#bdbdb3" :bold t))))
 '(gnus-summary-high-unread ((t (:bold t))))
 '(gnus-summary-low-ancient ((t (:foreground "#86b5e8"))))
 '(gnus-summary-low-read ((t (:foreground "#9ccc65"))))
 '(gnus-summary-low-ticked ((t (:foreground "#cd9595"))))
 '(gnus-summary-low-undownloaded ((t (:foreground "#757575"))))
 '(gnus-summary-low-unread ((t (:foreground nil :background nil))))
 '(gnus-summary-normal-ancient ((t (:inherit default))))
 '(gnus-summary-normal-read ((t (:foreground "#6aaf50"))))
 '(gnus-summary-normal-ticked ((t (:foreground "#df9522"))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "#858585"))))
 '(gnus-summary-normal-unread ((t (:foreground "#598bc1"))))
 '(gnus-summary-selected ((t (:underline t))))
 '(guide-key/prefix-command-face ((t (:foreground "#ab75c3"))))
 '(guide-key/highlight-command-face ((t (:foreground "#1d9a79"))))
 '(guide-key/key-face ((t (:foreground "#598bc1"))))
 '(helm-action ((t (:foreground "#baba36" :underline nil))))
 '(helm-bookmark-addressbook ((t (:foreground "#d65946"))))
 '(helm-bookmark-file ((t (:foreground "#68a5e9"))))
 '(helm-bookmark-gnus ((t (:foreground "#ab75c3"))))
 '(helm-bookmark-info ((t (:foreground "#6aaf50"))))
 '(helm-bookmark-man ((t (:foreground "#df9522"))))
 '(helm-bookmark-w3m ((t (:foreground "#baba36"))))
 '(helm-buffer-archive ((t (:foreground "#df9522"))))
 '(helm-buffer-directory ((t (:inherit dired-directory))))
 '(helm-buffer-file ((t (:foreground "#598bc1"))))
 '(helm-buffer-process ((t (:foreground "#6aaf50"))))
 '(helm-buffer-size ((t (:foreground "#df9522"))))
 '(helm-candidate-number ((t (:foreground "#1d9a79"))))
 '(helm-ff-directory ((t (:inherit dired-directory))))
 '(helm-ff-dotted-directory ((t (:inherit dired-directory))))
 '(helm-ff-dotted-symlink-directory ((t (:inherit helm-ff-dotted-directory :slant italic))))
 '(helm-ff-executable ((t (:foreground "#d65946"))))
 '(helm-ff-file ((t (:foreground "#598bc1"))))
 '(helm-ff-prefix ((t (:foreground "#d65946"))))
 '(helm-ff-socket ((t (:foreground "#ab75c3"))))
 '(helm-ff-symlink ((t (:inherit dired-symlink))))
 '(helm-grep-file ((t (:foreground "#598bc1" :underline t))))
 '(helm-grep-finish ((t (:foreground "#6aaf50"))))
 '(helm-grep-lineno ((t (:foreground "#608079"))))
 '(helm-header ((t (:foreground "#1a1a1a" :background "#bdbdb3"))))
 '(helm-locate-finish ((t (:foreground "#6aaf50"))))
 '(helm-M-x-key ((t (:foreground "#598bc1"))))
 '(helm-match-item ((t (:inherit match))))
 '(helm-match ((t (:inherit highlight :foreground "#baba36"))))
 '(helm-moccur-buffer ((t (:inherit compilation-info))))
 '(helm-prefarg ((t (:foreground "#6aaf50" :bold t))))
 '(helm-selection ((t (:background "#2b1147"))))
 '(helm-source-header ((t (:background "#404040"))))
 '(helm-visible-mark ((t (:inherit region))))
 '(helm-swoop-line-number-face ((t (:foreground "#608079"))))
 '(helm-swoop-target-word-face ((t (:inherit match))))
 '(helm-swoop-target-line-face ((t (:inherit highlight))))
 '(helm-swoop-target-line-block-face ((t (:inherit helm-swoop-target-line-face :foreground "#ffffff"))))
 '(highlight-indentation-current-column-face ((t (:background "#757575"))))
 '(highlight-indentation-face ((t (:background "#454545"))))
 '(hl-line ((t (:background "#112b47"))))
 '(flx-highlight-face ((t (:foreground "#68a5e9" :underline nil :bold t))))
 '(ido-only-match ((t (:foreground "#6aaf50"))))
 '(ido-first-match ((t (:foreground "#598bc1"))))
 '(ido-incomplete-regexp ((t (:foreground "#d65946"))))
 '(ido-subdir ((t (:foreground "#baba36"))))
 '(indent-guide-face ((t (:foreground "#454545"))))
 '(Info-quoted ((t (:inherit font-lock-constant-face))))
 '(info-menu-header ((t (:foreground "#858585" :weight bold :height 1.4))))
 '(info-menu-star ((t (:foreground "#d65946"))))
 '(info-node ((t (:foreground "#858585" :inherit italic :weight bold))))
 '(info-title-1 ((t (:weight bold :height 1.6))))
 '(info-title-2 ((t (:weight bold :height 1.4))))
 '(info-title-3 ((t (:weight bold :height 1.2))))
 '(info-title-4 ((t (:weight bold :height 1.0))))
 '(js2-external-variable ((t (:foreground "#df9522"))))
 '(js2-function-param ((t (:foreground "#1d9a79"))))
 '(js2-instance-member ((t (:foreground "#ab75c3"))))
 '(js2-jsdoc-html-tag-delimiter ((t (:foreground "#757575"))))
 '(js2-jsdoc-html-tag-name ((t (:foreground "#757575"))))
 '(js2-jsdoc-tag ((t (:foreground "#267E99"))))
 '(js2-jsdoc-type ((t (:foreground "#d65946"))))
 '(js2-jsdoc-value ((t (:foreground "#baba36"))))
 '(js2-private-function-call ((t (:foreground "#1d9a79"))))
 '(js2-private-member ((t (:foreground "#7d7c61"))))
 '(js2-warning ((t (:underline "#df9522"))))
 '(line-number ((t (:inherit default :foreground "#608079"))))
 '(line-number-current-line ((t (:inherit default :foreground "#1d9a79"))))
 '(makey-key-mode-button-face ((t (:inherit font-lock-constant-face))))
 '(message-cited-text ((t (:inherit font-lock-comment-face))))
 '(message-header-cc ((t (:foreground "#baba36"))))
 '(message-header-name ((t (:foreground "#df9522"))))
 '(message-header-newsgroups ((t (:foreground "#7d7c61" :bold t))))
 '(message-header-other ((t (:foreground "#608079"))))
 '(message-header-subject ((t (:foreground "#d65946"))))
 '(message-header-to ((t (:foreground "#1d9a79"))))
 '(message-header-xheader ((t (:foreground "#ab75c3"))))
 '(message-mml ((t (:foreground "#7d7c61"))))
 '(message-separator ((t (:foreground "#987654"))))
 '(minibuffer-prompt ((t (:foreground "#fffe0a" :bold nil))))
 '(mode-line ((t (:foreground "#bdbdb3" :background "#404040"))))
 '(mode-line-inactive ((t (:foreground "#858585" :background "#2b2b2b"))))
 '(mc/cursor-face ((t (:foreground "#000000" :background "#1d9a79"))))
 '(mc/cursor-bar-face ((t (:inherit mc/cursor-face :height 0.1))))
 '(org-agenda-date ((t (:foreground "#68a5e9"))))
 '(org-agenda-date-today ((t (:inherit org-agenda-date :bold t))))
 '(org-agenda-date-weekend ((t (:inherit org-agenda-date :slant italic))))
 '(org-agenda-done ((t (:foreground "#1d9a79"))))
 '(org-agenda-structure ((t (:foreground "#ab75c3"))))
 '(org-block-begin-line ((t (:inherit org-meta-line :underline "#454545"))))
 '(org-block-end-line ((t (:inherit org-meta-line :overline "#454545"))))
 '(org-checkbox ((t (:foreground "#7d7c61"))))
 '(org-date ((t (:inherit link))))
 '(org-date-selected ((t (:inherit highlight :foreground "#baba36"))))
 '(org-document-info ((t (:foreground "#8fbc8f"))))
 '(org-document-title ((t (:inherit org-document-info :bold t))))
 '(org-done ((t (:foreground "#1d9a79"))))
 '(org-todo ((t (:foreground "#d65946"))))
 '(org-ellipsis ((t (:foreground "#858585"))))
 '(org-hide ((t (:foreground "#1a1a1a"))))
 '(org-level-1 ((t (:foreground "#ab75c3"))))
 '(org-level-2 ((t (:foreground "#6aaf50"))))
 '(org-level-3 ((t (:foreground "#df9522"))))
 '(org-level-4 ((t (:foreground "#68a5e9"))))
 '(org-level-5 ((t (:foreground "#baba36"))))
 '(org-level-6 ((t (:foreground "#6aaf50"))))
 '(org-level-7 ((t (:foreground "#df9522"))))
 '(org-level-8 ((t (:foreground "#68a5e9"))))
 '(org-priority ((t (:foreground "#ad3632"))))
 '(org-scheduled ((t (:foreground "#6aaf50"))))
 '(org-scheduled-previously ((t (:foreground "#df9522"))))
 '(org-scheduled-today ((t (:foreground "#baba36"))))
 '(org-special-keyword ((t (:foreground "#608079"))))
 '(org-table ((t (:foreground "#86b5e8"))))
 '(org-tag ((t (:foreground "#267E99"))))
 '(org-time-grid ((t (:foreground "#608079"))))
 '(org-upcoming-deadline ((t (:inherit org-warning :bold nil))))
 '(org-warning ((t (:inherit font-lock-warning-face :foreground "#d65946"))))
 '(package-name ((t (:inherit link))))
 '(package-status-available ((t (:foreground "#6aaf50"))))
 '(package-description ((t (:foreground "#baba36"))))
 '(paradox-mode-line-face ((t (:foreground "#112b47" :bold t))))
 '(secondary-selection ((t (:background "#47112b"))))
 '(show-paren-match ((t (:foreground "#fffe0a" :underline t))))
 '(show-paren-mismatch ((t (:bold nil :inherit error))))
 '(undo-tree-visualizer-active-branch-face ((t (:inherit default))))
 '(undo-tree-visualizer-default-face ((t (:inherit font-lock-comment-face))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#df9522"))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#baba36"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#ab75c3"))))
 '(widget-field ((t (:foreground "#bdbdb3" :background "#353535"))))
 '(yas-field-highlight-face ((t (:background "#2b1147"))))
 '(default ((t (:background "gray5" :foreground "#bdbdb3" :weight normal)))))

(provide-theme 'nimbus)
